name       : freedink
version    : 109.6
release    : 4
source     :
    - https://ftp.gnu.org/gnu/freedink/freedink-109.6.tar.gz : 5e0b35ac8f46d7bb87e656efd5f9c7c2ac1a6c519a908fc5b581e52657981002
license    : GPL-3.0-or-later
component  : games.rpg
summary    : Free, portable and enhanced version of the Dink Smallwood game engine
description: |
    Dink Smallwood is an adventure/role-playing game, similar to classic Zelda (2D top view), made by RTsoft.
    The game features the twisted adventure of young Dink Smallwood, a pig farmer who leaves his town and goes on a quest to save the world.
builddeps  :
    - pkgconfig(SDL2_gfx)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(fontconfig)
    - pkgconfig(glm)
    - help2man
rundeps    :
    - freepats
setup      : |
    %patch -p1 < $pkgfiles/SDL2.10.patch
    %reconfigure --disable-tests
build      : |
    %make
install    : |
    %make_install
